apiVersion: v1
kind: Service
metadata:
  name: greeting-app-service
spec:
  selector:
    app: greeting-app-deployment-pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
      nodePort: 30002
  type: NodePort
  