apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app-deployment
  labels:
    app: greeting-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-app-deployment-pods
  template:
    metadata:
      name: greeting-app-deployment-pods
      labels:
        app: greeting-app-deployment-pods
    spec:
      containers:
        - name: greeting-container
          image: ogleh/islamic-greet:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
      